---
- hosts: development
  become: true
  tasks:

    - name: installa APACHE
      apt: 
        name: apache2 
        state: present 
        update_cache: yes

    - name: verifica che apache2 sia attivo
      service: 
        name: apache2
        state: started

    - name: installa modulo wsgi
      apt:
        name: libapache2-mod-wsgi
        state: present
        update_cache: yes

    - name: assicurati che il modulo wsgi sia attivo
      #apache2_module: state=present name=wsgi
      apache2_module: 
        state: present
        name: wsgi
      notify: restart apache2

    - name: carica index.html
      copy:
        src: ../files/index_apache.html
        dest: /var/www/html/index.html
        mode: 0755
      notify: restart apache2


  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted





