---
- name: install tools
  apt: name={{item}} state=present update_cache=yes
  loop:
    - python-mysqldb

- name: installa mysql
  apt: 
    name: mysql-server
    state: present
    update_cache: yes

- name: assicurati che mysql sia partito
  service:
    name: mysql
    state: started
    enabled: yes

- name: sovrascrivi riga per abilitare mysql all'esterno #da 127.0.0.1 a 0.0.0.0
  lineinfile:
    #dest: /etc/mysql/my.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf 
    regexp: ^bind-address 
    line: "bind-address = {{ansible_all_ipv4_addresses[0]}}" # sovrascrive 127.0.0.1 in my.cnf
  notify: restart mysql

- name: crea database demo
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: crea user per database
  mysql_user:
    name: "{{db_user_name}}"
    password: "{{ db_user_pass}}"
    priv: "{{ db_name }}.*:ALL" 
    host: "{{ db_user_host }}"
    state: present

