---
- hosts: development
  become: true
  tasks:

    - name: installa apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    #- name: assicurati che Apache sia attivo
    #  service: name=apache2 state=started enabled=yes

    - name: assicurati che Apache sia attivo
      service: 
        name: apache2
        state: started
        enabled: yes

