---
- hosts: loadbalancer
  become: true # operate as admin
  tasks:
    - name: installa NGINX
      apt: name=nginx state=present update_cache=yes

    - name: assicurati che NGINX sia attivo
      service: name=nginx state=started enabled=yes

    - name: copy index.html
      copy: src=files/nginx/index.html dest=/var/www/html/index.html mode=0755
      notify: restart nginx

    - name: configura nginx site
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/demo mode=0644
      notify: restart nginx

    - name: disattiva nginx configurazione di default
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify: restart nginx

    - name: attiva custom configurazione nginx
      file: src=/etc/nginx/sites-available/demo dest=/etc/nginx/sites-enabled/demo state=link
      notify: restart nginx



  handlers:

    - name: restart nginx
      service: name=nginx state=restarted
