---
# portare lo STACK giù ###
- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped

# Restart mysql
- hosts: database
  become: true
  tasks:
    - service: name=mysql state=restarted
    - wait_for: port=3306 state=started


# portare lo stack su ####
- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - service: name=nginx state=started
    - wait_for: port=80