---
- name: aggiungi elastic GPG Key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present


- name: installa apt-transport-https
  apt:
    name: apt-transport-https
    state: latest
    update_cache: yes

- name: aggiungi elasticsearch repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: installa elasticsearch
  apt:
    name: elasticsearch
    state: latest
    update_cache: yes
  notify: restart elasticsearch

- name: start elasticsearch
  service: name=elasticsearch state=started

- name: sovrascrivi riga per abilitare ip
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml 
    regexp: "^#network.host: 192.168.0.1"
    line: "network.host: 0.0.0.0" 
  notify: restart elasticsearch


- name: sovrascrivi riga per discovery.seed_hosts
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml 
    regexp: '^#discovery.seed_hosts: ["host1", "host2"]'
    line: 'discovery.seed_hosts: ["127.0.0.1", "0.0.0.0"]' 
  notify: restart elasticsearch

