---
# tasks file for nginx
- name: installa NGINX
  apt: name=nginx state=present

- name: assicurati che NGINX sia attivo
  service: name=nginx state=started enabled=yes

- name: copy index.html
  copy: src=files/nginx/index.html dest=/var/www/html/index.html mode=0755
  notify: restart nginx

- name: configura nginx site
  template: src=templates/nginx.conf.j2 dest="/etc/nginx/sites-available/{{ item.key }}" mode=0644
  with_dict: "{{sites}}"
  notify: restart nginx

- name: ottieni registri attivi # li salva in variabile active
  shell: ls -1 /etc/nginx/sites-enabled
  register: active

- name: disattiva nginx configurazione non in sites
  file: path="/etc/nginx/sites-enabled/{{item}}" state=absent
  with_items: "{{active.stdout_lines}}" #recupero dati da active
  when: item not in sites #se item non è uguale a variables in site /defaul.yml)
  notify: restart nginx

- name: attiva custom configurazione nginx
  file: src="/etc/nginx/sites-available/{{ item.key }}" dest="/etc/nginx/sites-enabled/{{ item.key }}" state=link
  with_dict: "{{sites}}"
  notify: restart nginx
