---
- hosts: development
  become: true
  tasks:

    - name: installa apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: assicurati che Apache sia attivo
      service: 
        name: apache2
        state: started
        enabled: yes

    - name: installa mod wsgi
      apt:
        name: libapache2-mod-wsgi
        state: present
        update_cache: yes

    - name: assicurati che mod wsgi sia attivo
      apache2_module: state=present name=wsgi
      notify: restart apache2

    - name: copy index.html
      copy: 
        src: files/apache2/index.html 
        dest: /var/www/html/index.html
        mode: 0755
      notify: restart apache2


  handlers:

    - name: restart apache2
      service: name=apache2 state=restarted

