---
- hosts: development
  become: true # operate as admin
  tasks:

    - name: disabilita modulo wsgi
      apache2_module: state=absent name=wsgi
      
    - name: stop apache
      service:
          name: apache2
          state: stopped

    - name: assicurati che APACHE non sia installato
      apt: 
        name: apache2 
        state: absent 
        update_cache: no
