---
- hosts: database
  become: true
  tasks:

    - name: installa mysql
      apt: 
        name: mysql-server
        state: present
        update_cache: yes

    - name: assicurati che mysql sia partito
      service:
        name: mysql
        state: started
        enabled: yes

    - name: sovrascrivi riga per abilitare mysql all'esterno #da 127.0.0.1 a 0.0.0.0
      lineinfile:
        #dest: /etc/mysql/my.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf 
        regexp: ^bind-address 
        line: "bind-address = 0.0.0.0" # sovrascrive 127.0.0.1 in my.cnf
      notify: restart mysql


  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
        