---
- hosts: database
  become: true
  tasks:

    - name: install tools
      apt: name={{item}} state=present update_cache=yes
      loop:
        - python-mysqldb

    - name: installa mysql
      apt: name=mysql-server state=present update_cache=yes

    - name: verica che mysql sia avviato
      service: name=mysql state=started enabled=yes

    - name: cambia riga bind-address
      lineinfile:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf 
        regexp: ^bind-address 
        line: "bind-address = 0.0.0.0" 
      notify: restart mysql

    - name: crea database demo
      mysql_db: name=demo state=present

    - name: crea utente db
      mysql_user: 
        name: demo
        password: demo
        priv: demo.*:ALL
        host: '%' 
        state: present

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted