---
- hosts: webserver
  become: true
  tasks:

    - name: installa apache2
      apt: name=apache2 state=present update_cache=yes

    - name: assicurati che apache sia attivo
      service: name=apache2 state=started enabled=yes

    - name: installa altri
      apt: name={{item}} state=present update_cache=yes
      loop:
        - build-essential
        - libssl-dev
        - curl
        - git

    - name: installa nodejs
      apt: name=nodejs state=latest update_cache=yes

    - name: installa npm
      apt: name=npm state=present update_cache=yes

    - name: copia app node
      copy: src=demo/ dest=/var/www/app mode=0755
      notify: restart apache2

    - name: abilita proxy
      apache2_module: state=present name=proxy
      notify: restart apache2

    - name: abilita proxy_http
      apache2_module: state=present name=proxy_http
      notify: restart apache2

      # sudo npm install -g pm2
    - name: install pm2 con npm 
      npm:
        name: pm2
        global: yes
        state: present

    - name: start daemon pm2 su app nodejs
      command: pm2 start app.js --name app chdir=/var/www/app
      ignore_errors: yes
      #when: npm_finished.changed


  handlers:

    - name: restart apache2
      service: name=apache2 state=restarted